import { useEffect, useMemo, useState } from "react";
import { Link2, ArrowRight, ArrowUpRight, BarChart3, Bell, BookOpen, Check, ChevronRight, CircleHelp, FileText, Github, Gauge, History, Home, Laptop, Link as LinkIcon, LogOut, Menu, Moon, QrCode, ScanLine, Shield, ShieldCheck, Smartphone, Sparkles, Sun, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";
import heroImage from "@/assets/payguard-hero.jpg";
import architectureImage from "@/assets/payguard-architecture-v2.jpg";
import AuthPage, { getAuthUser } from "./Auth";
import HomeDashboard from "./Home";

type Page = "home" | "studio" | "history" | "architecture" | "guide" | "login" | "signup" | "reset";
const getPage = (): Page => { const path = window.location.pathname.replace(/\/$/, ""); if (path === "/studio") return "studio"; if (path === "/history") return "history"; if (path === "/architecture") return "architecture"; if (path === "/guide") return "guide"; if (path === "/login") return "login"; if (path === "/signup") return "signup"; if (path === "/reset-password") return "reset"; return "home"; };

const navItems: { key: Page; label: string; icon: typeof Home }[] = [
  { key: "home", label: "Overview", icon: Home },
  { key: "studio", label: "Verification studio", icon: ScanLine },
  { key: "history", label: "Scan history", icon: History },
  { key: "architecture", label: "How it works", icon: Laptop },
  { key: "guide", label: "Safety guide", icon: BookOpen },
];

const scans = [
  { kind: "URL", title: "sbi-kyc-update.top", source: "URL inspector", score: 98, verdict: "Blocked", date: "Today · 10:42", color: "red" },
  { kind: "QR", title: "Blue Tokai Coffee", source: "Payment QR", score: 18, verdict: "Clear", date: "Yesterday · 18:06", color: "green" },
  { kind: "URL", title: "paytm-reward-claim.xyz", source: "URL inspector", score: 76, verdict: "Review", date: "Yesterday · 15:22", color: "amber" },
  { kind: "QR", title: "Apartment maintenance", source: "Payment QR", score: 34, verdict: "Clear", date: "02 Sep · 09:14", color: "green" },
  { kind: "URL", title: "parcel-track-support.com", source: "URL inspector", score: 64, verdict: "Review", date: "01 Sep · 21:38", color: "amber" },
];

function Logo() { return <span className="site-logo"><span className="site-logo-mark"><Shield size={17} /></span><strong>PayGuard</strong><em>AI</em></span>; }
function ThemeToggle({ dark, setDark }: { dark: boolean; setDark: (value: boolean) => void }) { return <button className="theme-toggle" onClick={() => setDark(!dark)} aria-label={dark ? "Switch to light mode" : "Switch to dark mode"}><span className={dark ? "active" : ""}><Moon size={13} /></span><span className={!dark ? "active" : ""}><Sun size={13} /></span></button>; }
function SiteNav({ dark, setDark, mobileOpen, setMobileOpen, signedIn }: { dark: boolean; setDark: (value: boolean) => void; mobileOpen: boolean; setMobileOpen: (value: boolean) => void; signedIn: boolean }) { return <header className="site-nav"><Link to="/" className="logo-link" onClick={() => setMobileOpen(false)}><Logo /></Link><nav className={`site-nav-links ${mobileOpen ? "open" : ""}`}>{navItems.map(({ key, label, icon: Icon }) => <Link key={key} to={key === "home" ? "/" : `/${key}`} className={getPage() === key ? "active" : ""} onClick={() => setMobileOpen(false)}><Icon size={15} />{label}</Link>)}</nav><div className="site-nav-actions"><div className="nav-status"><span />Protected</div>{signedIn ? <><Link to="/studio" className="nav-signin nav-account" onClick={() => setMobileOpen(false)}>Open studio</Link><button className="nav-signin nav-logout" onClick={() => window.dispatchEvent(new Event("payguard:logout"))} aria-label="Log out" title="Log out"><LogOut size={14} /></button></> : <Link to="/login" className="nav-signin" onClick={() => setMobileOpen(false)}>Sign in <ArrowUpRight size={13} /></Link>}<ThemeToggle dark={dark} setDark={setDark} /><button className="nav-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open navigation">{mobileOpen ? <X size={19} /> : <Menu size={19} />}</button></div></header>; }
function Footer() { return <footer className="site-footer"><Logo /><span>Stateless protection for safer payment moments.</span><span className="footer-right">© 2026 PayGuard AI · <button onClick={() => toast.info("Privacy documentation is coming soon.")}>Privacy by design</button></span></footer>; }
function CTA({ children = "Open verification studio" }: { children?: React.ReactNode }) { return <Link to="/login" className="site-button primary">{children}<ArrowUpRight size={15} /></Link>; }

function Landing() { return <>
  <section className="landing-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(35,31,27,.95) 0%, rgba(35,31,27,.78) 45%, rgba(35,31,27,.12) 100%), url(${heroImage})` }}><div className="landing-hero-copy"><div className="hero-eyebrow"><Sparkles size={13} /> PROACTIVE PAYMENT PROTECTION</div><h1>Know before<br /><em>you tap.</em></h1><p>PayGuard AI gives every payment, message, and QR code a second opinion — so a moment of pressure doesn’t become a costly mistake.</p><div className="hero-ctas"><CTA>Get started <ArrowRight size={15} /></CTA><Link to="/guide" className="text-cta">See how it works <ChevronRight size={14} /></Link></div><div className="hero-trust"><span><ShieldCheck size={14} /> Private by design</span><span><Zap size={14} /> Instant signals</span><span><Check size={14} /> No data stored</span></div></div><div className="hero-caption"><span>01</span><span>Trust, before tap.</span></div></section>
  <section className="landing-intro page-section"><div className="section-intro"><span className="eyebrow">A CALMER WAY TO CHECK</span><h2>Clarity at the<br /><em>right moment.</em></h2></div><div className="intro-copy"><p>Scams are designed to make you rush. PayGuard slows the moment down and makes the important signals visible — in plain English, without storing your sensitive inputs.</p><CTA>Try a sample check</CTA></div></section>
  <section className="feature-grid page-section"><Feature icon={ScanLine} number="01" title="Scan anything suspicious" text="Drop in a screenshot, paste a message, inspect a URL, or point your camera at a QR code." /><Feature icon={BarChart3} number="02" title="Understand the signals" text="See a focused risk score, the exact warning signs, and a clear explanation of what they mean." /><Feature icon={ShieldCheck} number="03" title="Act with confidence" text="Get an immediate recommendation before you open, scan, approve, or share anything." /></section>
  <section className="landing-band"><div><span className="eyebrow">DESIGNED FOR REAL MOMENTS</span><h2>One studio.<br /><em>Four ways to verify.</em></h2></div><div className="band-modes"><span><FileText size={17} /> SMS & chats</span><span><LinkIcon size={17} /> URLs</span><span><QrCode size={17} /> QR codes</span><span><Smartphone size={17} /> Camera</span></div></section>
</>; }
function Feature({ icon: Icon, number, title, text }: { icon: typeof ScanLine; number: string; title: string; text: string }) { return <article className="feature-card"><span className="feature-number">{number}</span><span className="feature-icon"><Icon size={19} /></span><h3>{title}</h3><p>{text}</p><ArrowUpRight size={16} className="feature-arrow" /></article>; }

function HistoryPage() { const [filter, setFilter] = useState<"all" | "URL" | "QR">("all"); const visible = useMemo(() => filter === "all" ? scans : scans.filter((scan) => scan.kind === filter), [filter]); return <PageFrame eyebrow="YOUR PROTECTION LOG" title={<>Scan history, <em>made useful.</em></>} subtitle="A clear record of the links and QR codes you have checked — with patterns you can actually act on."><div className="analytics-grid"><div className="analytics-card primary-metric"><span className="metric-label">TOTAL CHECKS</span><strong>42</strong><span className="metric-trend"><ArrowUpRight size={13} /> 18% vs last month</span><div className="spark-bars">{[38,52,42,68,46,76,62,88,73,94,81,100].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></div><div className="analytics-card"><span className="metric-label">URL SCANS</span><strong>27</strong><span className="metric-muted">64% of activity</span><div className="donut url-donut"><span>64%</span></div></div><div className="analytics-card"><span className="metric-label">QR SCANS</span><strong>15</strong><span className="metric-muted">36% of activity</span><div className="donut qr-donut"><span>36%</span></div></div><div className="analytics-card"><span className="metric-label">THREATS CAUGHT</span><strong className="danger-number">11</strong><span className="metric-muted">Would-be scams blocked</span><div className="threat-meter"><span style={{ width: "72%" }} /></div></div></div><div className="history-panel"><div className="history-panel-top"><div><span className="eyebrow">ACTIVITY TIMELINE</span><h3>Previously analysed</h3></div><div className="filter-tabs">{(["all", "URL", "QR"] as const).map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item === "all" ? "All scans" : `${item} scans`}</button>)}</div></div><div className="history-list">{visible.map((scan) => <div className="history-item" key={scan.title}><span className={`history-kind ${scan.kind.toLowerCase()}`}>{scan.kind === "URL" ? <Link2 size={15} /> : <QrCode size={15} />}</span><div className="history-item-copy"><strong>{scan.title}</strong><span>{scan.source}</span></div><span className={`history-verdict ${scan.color}`}><i />{scan.verdict}</span><span className="history-score">{scan.score}<small>/100</small></span><span className="history-date">{scan.date}</span><button className="history-open" onClick={() => toast.info(`${scan.title} was analysed ${scan.date.toLowerCase()}.`)}><ArrowUpRight size={15} /></button></div>)}</div></div></PageFrame>; }

function ArchitecturePage() { return <PageFrame eyebrow="UNDER THE HOOD" title={<>A safety layer built for <em>the last second.</em></>} subtitle="PayGuard combines local parsing, reputation checks, and semantic reasoning into one stateless decision loop."><div className="architecture-visual"><img src={architectureImage} alt="Illustrated PayGuard AI system architecture showing inputs flowing through a shield risk engine to safe and blocked outcomes" /><div className="architecture-label label-input"><span>01</span> INTAKE</div><div className="architecture-label label-engine"><span>02</span> RISK ENGINE</div><div className="architecture-label label-output"><span>03</span> OUTCOME</div></div><div className="architecture-grid"><ArchitectureStep index="01" title="Inputs stay close" icon={Smartphone} text="Screenshots, raw text, links, and QR payloads enter through the same verification surface. Nothing is persisted." /><ArchitectureStep index="02" title="Signals become context" icon={Gauge} text="OCR, QR parsing, domain checks, and intent evaluation are composited into one explainable score." /><ArchitectureStep index="03" title="The next action is clear" icon={ShieldCheck} text="The user receives a calm, plain-English recommendation: continue, review, or stop." /></div><div className="architecture-note"><Shield size={18} /><div><strong>Stateless by design</strong><span>Every analysis is an in-memory transaction. The service returns a structured result and forgets the input.</span></div><Link to="/guide">Read the safety guide <ArrowRight size={14} /></Link></div></PageFrame>; }
function ArchitectureStep({ index, title, icon: Icon, text }: { index: string; title: string; icon: typeof Gauge; text: string }) { return <div className="architecture-step"><span className="step-index">{index}</span><span className="step-icon"><Icon size={18} /></span><h3>{title}</h3><p>{text}</p></div>; }

function GuidePage() { const steps = [{ title: "Start with the thing that feels off", text: "Open the Verification studio and choose the input that matches what you received: screenshot, message, URL, or camera.", icon: ScanLine }, { title: "Give PayGuard the full context", text: "Paste the whole message or full URL. Include sender names and urgency language — those details make the result more useful.", icon: FileText }, { title: "Read the recommendation", text: "Use the score as a signal, not a verdict. Review the breakdown, then follow the recommended action before paying.", icon: BookOpen }, { title: "When in doubt, stop", text: "Never share a UPI PIN to receive money. Contact the organisation through a number or site you find independently.", icon: ShieldCheck }]; return <PageFrame eyebrow="A SHORT SAFETY GUIDE" title={<>Four calm steps to <em>stay safer.</em></>} subtitle="PayGuard is a second opinion, not a replacement for your judgement. This is how to make that second opinion count."><div className="guide-layout"><div className="guide-steps">{steps.map((step, i) => { const Icon = step.icon; return <div className="guide-step" key={step.title}><span className="guide-step-num">0{i + 1}</span><span className="guide-step-icon"><Icon size={18} /></span><div><h3>{step.title}</h3><p>{step.text}</p></div></div>; })}</div><aside className="guide-aside"><div className="guide-aside-top"><CircleHelp size={19} /><span>REMEMBER THIS</span></div><h3>Receiving money never requires your UPI PIN.</h3><p>A PIN authorises money leaving your account. If someone asks for it to receive a refund, reward, or cashback, stop.</p><div className="guide-callout"><ShieldCheck size={16} /><span>Save this rule</span></div></aside></div><div className="guide-cta"><div><span className="eyebrow">READY WHEN YOU ARE</span><h2>Make the next tap a<br /><em>more informed one.</em></h2></div><CTA>Get started</CTA></div></PageFrame>; }

function PageFrame({ eyebrow, title, subtitle, children }: { eyebrow: string; title: React.ReactNode; subtitle: string; children: React.ReactNode }) { return <main className="page-frame"><section className="page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></section>{children}</main>; }

export default function Site() { const [page, setPage] = useState(getPage); const [dark, setDark] = useState(() => localStorage.getItem("payguard-theme") === "dark"); const [mobileOpen, setMobileOpen] = useState(false); const [user, setUser] = useState(getAuthUser); const signedIn = Boolean(user); useEffect(() => { const onPop = () => setPage(getPage()); const onLogout = () => { localStorage.removeItem("payguard-user"); localStorage.removeItem("payguard-session"); setUser(null); window.history.pushState({}, "", "/"); setPage("home"); toast.success("You have been logged out."); }; window.addEventListener("popstate", onPop); window.addEventListener("payguard:logout", onLogout); return () => { window.removeEventListener("popstate", onPop); window.removeEventListener("payguard:logout", onLogout); }; }, []); useEffect(() => { document.documentElement.classList.toggle("dark", dark); localStorage.setItem("payguard-theme", dark ? "dark" : "light"); }, [dark]); useEffect(() => { const onClick = (event: MouseEvent) => { const target = (event.target as HTMLElement).closest("a"); if (!target || !target.href.startsWith(window.location.origin)) return; event.preventDefault(); const url = new URL(target.href); window.history.pushState({}, "", url.pathname); setPage(getPage()); window.scrollTo({ top: 0, behavior: "smooth" }); }; document.addEventListener("click", onClick); return () => document.removeEventListener("click", onClick); }, []); const onAuthSuccess = (nextUser: { email: string; name: string }) => { setUser(nextUser); window.history.pushState({}, "", "/studio"); setPage("studio"); window.scrollTo({ top: 0, behavior: "smooth" }); }; const protectedPage = page === "studio" || page === "history"; return <div className="site-shell">{page === "login" || page === "signup" || page === "reset" ? <AuthPage mode={page === "reset" ? "reset" : page} onSuccess={onAuthSuccess} /> : <><SiteNav dark={dark} setDark={setDark} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} signedIn={signedIn} />{protectedPage && !signedIn ? <AuthPage mode="login" onSuccess={onAuthSuccess} /> : page === "studio" ? <HomeDashboard /> : page === "history" ? <HistoryPage /> : page === "architecture" ? <ArchitecturePage /> : page === "guide" ? <GuidePage /> : <Landing />}<Footer /></>}</div>; }
