from pathlib import Path
path = Path(__file__).parents[1] / "client/src/pages/Site.tsx"
text = path.read_text()
text = text.replace('import architectureImage from "@/assets/payguard-architecture.jpg";', 'import architectureImage from "@/assets/payguard-architecture-v2.jpg";\nimport AuthPage, { getAuthUser } from "./Auth";')
text = text.replace('type Page = "home" | "studio" | "history" | "architecture" | "guide";', 'type Page = "home" | "studio" | "history" | "architecture" | "guide" | "login" | "signup";')
text = text.replace('const getPage = (): Page => { const path = window.location.pathname.replace(/\\/$/, ""); if (path === "/studio") return "studio"; if (path === "/history") return "history"; if (path === "/architecture") return "architecture"; if (path === "/guide") return "guide"; return "home"; };', 'const getPage = (): Page => { const path = window.location.pathname.replace(/\\/$/, ""); if (path === "/studio") return "studio"; if (path === "/history") return "history"; if (path === "/architecture") return "architecture"; if (path === "/guide") return "guide"; if (path === "/login") return "login"; if (path === "/signup") return "signup"; return "home"; };')
old_nav = 'function SiteNav({ dark, setDark, mobileOpen, setMobileOpen }: { dark: boolean; setDark: (value: boolean) => void; mobileOpen: boolean; setMobileOpen: (value: boolean) => void }) { return <header className="site-nav"><Link to="/" className="logo-link" onClick={() => setMobileOpen(false)}><Logo /></Link><nav className={`site-nav-links ${mobileOpen ? "open" : ""}`}>{navItems.map(({ key, label, icon: Icon }) => <Link key={key} to={key === "home" ? "/" : `/${key}`} className={getPage() === key ? "active" : ""} onClick={() => setMobileOpen(false)}><Icon size={15} />{label}</Link>)}</nav><div className="site-nav-actions"><div className="nav-status"><span />Protected</div><ThemeToggle dark={dark} setDark={setDark} /><button className="nav-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open navigation">{mobileOpen ? <X size={19} /> : <Menu size={19} />}</button></div></header>; }'
new_nav = 'function SiteNav({ dark, setDark, mobileOpen, setMobileOpen, signedIn }: { dark: boolean; setDark: (value: boolean) => void; mobileOpen: boolean; setMobileOpen: (value: boolean) => void; signedIn: boolean }) { return <header className="site-nav"><Link to="/" className="logo-link" onClick={() => setMobileOpen(false)}><Logo /></Link><nav className={`site-nav-links ${mobileOpen ? "open" : ""}`}>{navItems.map(({ key, label, icon: Icon }) => <Link key={key} to={key === "home" ? "/" : `/${key}`} className={getPage() === key ? "active" : ""} onClick={() => setMobileOpen(false)}><Icon size={15} />{label}</Link>)}</nav><div className="site-nav-actions"><div className="nav-status"><span />Protected</div>{signedIn ? <Link to="/studio" className="nav-signin nav-account" onClick={() => setMobileOpen(false)}>Open studio</Link> : <Link to="/login" className="nav-signin" onClick={() => setMobileOpen(false)}>Sign in <ArrowUpRight size={13} /></Link>}<ThemeToggle dark={dark} setDark={setDark} /><button className="nav-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open navigation">{mobileOpen ? <X size={19} /> : <Menu size={19} />}</button></div></header>; }'
if old_nav not in text: raise SystemExit('nav not found')
text = text.replace(old_nav, new_nav)
text = text.replace('function CTA({ children = "Open verification studio" }: { children?: React.ReactNode }) { return <Link to="/studio" className="site-button primary">{children}<ArrowUpRight size={15} /></Link>; }', 'function CTA({ children = "Open verification studio" }: { children?: React.ReactNode }) { return <Link to="/login" className="site-button primary">{children}<ArrowUpRight size={15} /></Link>; }')
old_site = 'export default function Site() { const [page, setPage] = useState(getPage); const [dark, setDark] = useState(() => localStorage.getItem("payguard-theme") === "dark"); const [mobileOpen, setMobileOpen] = useState(false); useEffect(() => { const onPop = () => setPage(getPage()); window.addEventListener("popstate", onPop); return () => window.removeEventListener("popstate", onPop); }, []); useEffect(() => { document.documentElement.classList.toggle("dark", dark); localStorage.setItem("payguard-theme", dark ? "dark" : "light"); }, [dark]); useEffect(() => { const onClick = (event: MouseEvent) => { const target = (event.target as HTMLElement).closest("a"); if (!target || !target.href.startsWith(window.location.origin)) return; event.preventDefault(); const url = new URL(target.href); window.history.pushState({}, "", url.pathname); setPage(getPage()); window.scrollTo({ top: 0, behavior: "smooth" }); }; document.addEventListener("click", onClick); return () => document.removeEventListener("click", onClick); }, []); return <div className="site-shell"><SiteNav dark={dark} setDark={setDark} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} />{page === "studio" ? <HomeDashboard /> : page === "history" ? <HistoryPage /> : page === "architecture" ? <ArchitecturePage /> : page === "guide" ? <GuidePage /> : <Landing />}<Footer /></div>; }'
new_site = 'export default function Site() { const [page, setPage] = useState(getPage); const [dark, setDark] = useState(() => localStorage.getItem("payguard-theme") === "dark"); const [mobileOpen, setMobileOpen] = useState(false); const [user, setUser] = useState(getAuthUser); const signedIn = Boolean(user); useEffect(() => { const onPop = () => setPage(getPage()); window.addEventListener("popstate", onPop); return () => window.removeEventListener("popstate", onPop); }, []); useEffect(() => { document.documentElement.classList.toggle("dark", dark); localStorage.setItem("payguard-theme", dark ? "dark" : "light"); }, [dark]); useEffect(() => { const onClick = (event: MouseEvent) => { const target = (event.target as HTMLElement).closest("a"); if (!target || !target.href.startsWith(window.location.origin)) return; event.preventDefault(); const url = new URL(target.href); window.history.pushState({}, "", url.pathname); setPage(getPage()); window.scrollTo({ top: 0, behavior: "smooth" }); }; document.addEventListener("click", onClick); return () => document.removeEventListener("click", onClick); }, []); const onAuthSuccess = (nextUser: { email: string; name: string }) => { setUser(nextUser); window.history.pushState({}, "", "/studio"); setPage("studio"); window.scrollTo({ top: 0, behavior: "smooth" }); }; const protectedPage = page === "studio" || page === "history"; return <div className="site-shell">{page === "login" || page === "signup" ? <AuthPage mode={page} onSuccess={onAuthSuccess} /> : <><SiteNav dark={dark} setDark={setDark} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} signedIn={signedIn} />{protectedPage && !signedIn ? <AuthPage mode="login" onSuccess={onAuthSuccess} /> : page === "studio" ? <HomeDashboard /> : page === "history" ? <HistoryPage /> : page === "architecture" ? <ArchitecturePage /> : page === "guide" ? <GuidePage /> : <Landing />}<Footer /></>}</div>; }'
if old_site not in text: raise SystemExit('site not found')
text = text.replace(old_site, new_site)
path.write_text(text)
print('auth flow added')
